# Generated by Django 4.1.3 on 2023-04-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('date_of_expense', models.IntegerField(default=0)),
                ('amount', models.CharField(default=' ', max_length=100)),
                ('user_name', models.CharField(default=' ', max_length=100)),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.CharField(default=' ', max_length=30)),
            ],
        ),
    ]
