# Generated by Django 4.1.3 on 2023-04-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_expenses_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_of_expense',
            field=models.CharField(default=' ', max_length=70),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='updated_at',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
